<a href="https://colab.research.google.com/github/krishnamurtv1/Codepath/blob/main/CSIT553_class2_1_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# only run once
!git clone https://github.com/profliuhao/CSIT553.git

Cloning into 'CSIT553'...
remote: Enumerating objects: 190, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 190 (delta 16), reused 2 (delta 2), pack-reused 160 (from 1)
Receiving objects: 100% (190/190), 5.74 MiB | 14.12 MiB/s, done.
Resolving deltas: 100% (83/83), done.

# CSIT 553 Class 2.1 Eexercise: Numpy and Pandas

### Instruction
The file name is data.csv. It contains the information of all municipalities in New Jersery. The meaning of each colunmn is as follows:

* Municipality: the name of the municipality
* County: the county that the municipality belongs to
* POP2010: the population of a municipality in 2010
* POP2017: the population of a municipality in 2017
* MunicipalType: the type of a municipality

In this exercise, please use the functions and operations in pandas to answer the following questions.

In [2]:
# import pandas

import pandas as pd

## Exercise 0
Read the file data.csv as a dataFrame named **df**. Assign the column 'Municipal' as the row index.   
  
#### Note  
1. Use **read_csv** to read the file to be a dataFrame
2. Set the argument **index_col** to be the name of the first column
3. Set the argument **thousands** to be ',' since there are thousand separators in the file

In [3]:
# file_dir = 'data.csv'
file_dir = '/content/CSIT553/Module_2/CSIT553_class2_exercise/data.csv'
df = pd.read_csv (file_dir, thousands=',', index_col="Municipality")
df

                         County  POP2010  POP2017 MunicipalType
Municipality
Aberdeen               Monmouth    18157    18232      Township
Absecon                Atlantic     8411     8283          City
Alexandria Township   Hunterdon     4938     4805      Township
Allamuchy                Warren     4323     4644      Township
Allendale                Bergen     6505     6906       Borough
...                         ...      ...      ...           ...
Woodlynne                Camden     2978     2947       Borough
Woodstown                 Salem     3505     3454       Borough
Woolwich Township    Gloucester    10200    12472      Township
Wrightstown          Burlington      802      785       Borough
Wyckoff                  Bergen    16635    16941      Township

[565 rows x 4 columns]

## Exercise 1
What is the municipality with the most population in 2017?

In [5]:
# You should write your answer within this cell
# write your code of exercise 1 here
df['POP2017'].idxmax()

'Newark'

## Exercise 2
How many municipalities are there in each county? The output should be a Series with the county name as the index and the number as the value.  
#### Hint:
Choose the column of 'County' and use **values_counts** function to calculate the frequencies of values in that column.

In [7]:
# You should write your answer within this cell
# write your code of exercise 2 here
df['County'].value_counts()

County
Bergen        70
Monmouth      53
Burlington    40
Morris        39
Camden        37
Ocean         33
Hunterdon     26
Middlesex     25
Gloucester    24
Sussex        24
Atlantic      23
Warren        22
Essex         22
Union         21
Somerset      21
Cape May      16
Passaic       16
Salem         15
Cumberland    14
Hudson        12
Mercer        12
Name: count, dtype: int64

## Exercise 3
Which municipality has the largest increasing in population from 2010 to 2017?
The output should be a string.

In [9]:
# You should write your answer within this cell
# write your code of exercise 3 here
(df['POP2017']-df['POP2010']).idxmax()

'Jersey City'

## Exercise 4
What is the total population of the Essex county in 2017? The output should be an integer.
#### Hint
1. Create a new dataFrame which selects the rows that are 'Essex' in the column 'County'
2. Choose the column 'POP2017' of the new dataFrame
3. Apply sum method to get the sum of that column

In [11]:
# You should write your answer within this cell
# write your code of exercise 4 here
df2 = df[df['County']=='Essex']
sum(df2['POP2017'])

807959

## Exercise 5
Find the top five municipalities in population of 2017. List their county and the population of 2017. The output should be a dataFrame with two columns 'County' and 'POP2017', and the municipality as the index.

#### Hint
1. Sort **df** by the values in the column 'POP2017' in descending order.
2. Choose the first 5 rows of the sorted **df**, and select their columns 'County' and 'POP2017'

In [12]:
# You should write your answer within this cell
# write your code of exercise 5 here
df.sort_values(by='POP2017', ascending=False).head()[['County', 'POP2017']]

               County  POP2017
Municipality
Newark          Essex   285154
Jersey City    Hudson   270753
Paterson      Passaic   148678
Elizabeth       Union   130215
Lakewood        Ocean   102682

## Exercise 6
What is the name of the township with the most population in 2010?

In [13]:
# You should write your answer within this cell
# write your code of exercise 6 here
df[df['MunicipalType']=='Township']['POP2010'].idxmax()

'Edison'